export enum Events {
  CREATE_PLAYER = "CREATE_PLAYER",
  RECONNECT = "RECONNECT",
  CREATE_ROOM = "CREATE_ROOM",
  JOIN_ROOM = "JOIN_ROOM",
  LEAVE_ROOM = "LEAVE_ROOM",
  START_GAME = "START_GAME",
  START_ROUND = "START_ROUND",
  NOTIFY_DRAWER = "NOTIFY_DRAWER",
  SELECT_WORD = "SELECT_WORD",
  SELECT_TIMEOUT = "SELECT_TIMEOUT",
  START_DRAW = "START_DRAW",
  DRAW = "DRAW",
  GUESS_WORD = "GUESS_WORD",
  END_DRAW = "END_DRAW",
  END_GAME = "END_GAME",
}

export interface WsPayload {
  event: Events;
  correlationId?: string;
  data: any;
}
