export enum Events {
  CREATE_PLAYER = "CREATE_PLAYER",
  CREATE_ROOM = "CREATE_ROOM",
  JOIN_ROOM = "JOIN_ROOM",
  LEAVE_ROOM = "LEAVE_ROOM",
  START_GAME = "START_GAME",
  START_ROUND = "START_ROUND",
  NOTIFY_DRAWER = "NOTIFY_DRAWER",
  SELECT_WORD = "SELECT_WORD",
  SELECT_TIMEOUT = "SELECT_TIMEOUT",
  START_DRAW = "START_DRAW",
  END_GAME = "END_GAME",
}

export interface WsEvent {
  event: Events;
  payload: any;
}
